version: '3.9'

services:
  patrikShop:
    image: postgres:17.4
    container_name: patrikShop
    restart: always
    ports:
      - 5435:5435
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data